//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.23 at 10:17:01 AM PDT 
//


package test.support.beans;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the test.support.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TestSub_QNAME = new QName("", "test_sub");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: test.support.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TestPropertyTwo }
     * 
     */
    public TestPropertyTwo createTestPropertyTwo() {
        return new TestPropertyTwo();
    }

    /**
     * Create an instance of {@link TestBean }
     * 
     */
    public TestBean createTestBean() {
        return new TestBean();
    }

    /**
     * Create an instance of {@link TestPropertyOne }
     * 
     */
    public TestPropertyOne createTestPropertyOne() {
        return new TestPropertyOne();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "test_sub")
    public JAXBElement<String> createTestSub(String value) {
        return new JAXBElement<String>(_TestSub_QNAME, String.class, null, value);
    }

}
