//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.23 at 10:17:01 AM PDT 
//


package test.support.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}testProperty_one"/>
 *         &lt;element ref="{}testProperty_two"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "testPropertyOne",
    "testPropertyTwo"
})
@XmlRootElement(name = "testBean")
public class TestBean {

    @XmlElement(name = "testProperty_one", required = true)
    protected TestPropertyOne testPropertyOne;
    @XmlElement(name = "testProperty_two", required = true)
    protected TestPropertyTwo testPropertyTwo;

    /**
     * Gets the value of the testPropertyOne property.
     * 
     * @return
     *     possible object is
     *     {@link TestPropertyOne }
     *     
     */
    public TestPropertyOne getTestPropertyOne() {
        return testPropertyOne;
    }

    /**
     * Sets the value of the testPropertyOne property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestPropertyOne }
     *     
     */
    public void setTestPropertyOne(TestPropertyOne value) {
        this.testPropertyOne = value;
    }

    /**
     * Gets the value of the testPropertyTwo property.
     * 
     * @return
     *     possible object is
     *     {@link TestPropertyTwo }
     *     
     */
    public TestPropertyTwo getTestPropertyTwo() {
        return testPropertyTwo;
    }

    /**
     * Sets the value of the testPropertyTwo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestPropertyTwo }
     *     
     */
    public void setTestPropertyTwo(TestPropertyTwo value) {
        this.testPropertyTwo = value;
    }

}
